<?php
$customerId = Mage::getSingleton('customer/session')->getId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$bidNumber = $customer->getBidCustomer();
?>
<div class="col-main">
<!--    <div class="page-title">-->
<!--        <h1>My Bids</h1>-->
<!--    </div>-->
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Your bid number')?></h2>
            <div class="form-list">
                <label for="content"><?php echo $this->__('Bid Number: ')?></label>
                <span class="input-box">
                    <?php echo $bidNumber;?>
                    <span><?php echo $this->__('Bid')?></span>
                </span>


            </div>
            <!--        <div class="row" id="bidder_name_form_button" style="">-->
            <!--            <button class="button" style="float:right" type="submit">-->
            <!--                <span>Buy Bid more</span>-->
            <!--            </button>-->
            <!--        </div>-->
    <style type="text/css">
    </style>
            </div>
</div>